### ISSUE TITLE
RPED - Rapid Parts Exchanging Device - Causing Dreamseeker hard crash.

### ISSUE THREAD

**Issue by DemgelZalvine** [SpadesNeil/VOREstation#56] opened 2015-10-02 03:48 UTC
As of me writing this, if you mess with the inventory of a RPED, it will start placing random objects in your hand. Further, if you try to put them back or put the RPED down on the ground it will cause your client to hard crash. Requiring a full reset of BYOND in order to be able to reconnect to the server. I can't replicate the problem to a T, but persistantly crash upon using it.

**Comment by OrbisAnima** [comment] 2015-10-02 13:26
I will try to duplicate it locally, with +DEBUG, and see what I can glimpse

**Comment by OrbisAnima** [comment] 2015-10-04 18:57
Couldn't Reproduce :(

**Comment by SpadesNeil** [comment] 2015-10-05 02:26
If this bug cannot be reproduced, I will mark it as invalid in a few days and close it.

**Comment by SpadesNeil** [comment] 2015-10-13 22:01
RE OPEN YOU FUCK. *kicks Github* :|

**Comment by Leshana** [comment] 2015-10-17 21:15
I cannot reproduce the crash, but I certainly can reproduce the "apparent duplicate item" issue.
Steps:
1. Fill the Part Replacer with at two of something.
2. Open Part Replacer's inventory.
3. Take one of the items into your hand.
4. Put it back into the Part Replacer
The Part Replacer's inventory will show 2 of the item, but you will still see it in your hand.  However attempts to use it will fail (its not actually there).   Even closing and re-opening the part replacer's inventory will not fix this glitch!

**Closed** 2015-10-18 01:21 UTC
Labels: bug, help wanted
