### ISSUE TITLE
Upgrading the destructive analyzer actually makes it worse!

### ISSUE THREAD

**Issue by Treasa729** [SpadesNeil/VOREstation#169] opened 2015-10-19 10:09 UTC
When the destructive analyzer is outfitted with better parts, it is supposed to be able to deconstruct lower reliability items, but when upgraded, it has the opposite effect! Things that it would be able to deconstruct without upgrades can no longer be deconstructed, even if they have the same reliability!

   I verified this myself by upgrading the analyzer with full reliability parts, (So that's not part of the issue) and tried to deconstruct an item with 90 reliability with no success. After re-outfitting it with the stock, weakest parts, it was able to deconstruct the same item, not remade or anything else!

   In addition, the analyzer, unupgraded puts 60% of the scanned material into the protolathe's material storage, wheras the upgraded analyzer gives none of the material back at all!

**Comment by Arokha** [comment] 2015-10-19 10:24
Probably a less-than greater-than math problem in the code.

**Comment by SpadesNeil** [comment] 2015-10-19 18:06
Oh. Wow. Bay never fixed this. I fixed this bug in the last code, told them, and then... ugh...

I'll look at it later... -_-

**Comment by SpadesNeil** [comment] 2015-10-19 23:17
I think the issue lies here.
[code]/obj/machinery/r_n_d/destructive_analyzer/RefreshParts()
	var/T = 0
	for(var/obj/item/weapon/stock_parts/S in src)
		T += S.rating
	decon_mod = T * 0.1
	min_reliability = 93 - T[/code]

**Comment by Arokha** [comment] 2015-10-23 11:13
The decon_mod line is definitely wrong. That's a multiplier for how many materials it gives back. It starts at 1.

Each part has a 'rating' and the default for the stock 3 parts is all 1, so you would think it should be a modifier of 1, sure.

But what it APPEARS they were TRYING to do is take the 1 as a base then sum up the ratings and multiply them by 0.1, to get like... 1.6 reliability if you put in three rating 2 parts. That... is not what that math does. This can be fixed by making that:
> decon_mod = (T * 0.1) + 1

But even then, simply taking out the starting parts and putting them back gives you 1.3, so I am not sure they thought this through.

I'll rewrite the whole section.

**Comment by Arokha** [comment] 2015-10-23 11:27
> min_reliability = 93 - T

This appears to make sense, though. I'm not sure why this would cause issues. I'll have to test it ingame.

**Comment by Arokha** [comment] 2015-10-23 12:18
I just realized that it's working exactly as intended, however they have it set to be 100% efficient at map load, and then the first time RefreshParts() is called, brings it back down to 30% like a reasonable thing.

The other misleading thing is that the Protolathe, with upgrades, also becomes more efficient. For example, making a high-capacity battery might take 350 metal and 30 glass, and give back 60% of that, but the high-cap battery in robotics that comes with the map is 700 metal and 60 glass. So even items of the same type, when deconstructed, might give varying amounts. The only way to see this is with view variables and looking at the materials var.

I actually don't see any other issues with it. I've followed it from start to finish of that process and it makes sense.

**Comment by Arokha** [comment] 2015-10-23 12:50
This ... is actually several issues, and seems to be caused by inconsistencies between coders.

1) When deconstructed, (some?) machines do not actually remove the parts they give back from their contents. Instead they keep those, and then just forget that they have them, asking for their construction parts again to get rebuilt. So deconstructing and reconstructing the DA for example several times, you can end up with like 5 of every part inside it.

2) Some coders use var/contents to get what parts a machine has, and some use var/component_parts. The latter seems to always be accurate. On the DA though, it uses contents, and gets some insane results with the tons of parts it ends up having.

**Comment by Arokha** [comment] 2015-10-23 13:00
Opened #204 about the machine contents issue. This issue can be closed when #203 is merged.

**Closed** 2015-10-23 18:29 UTC
Labels: bug
