### ISSUE TITLE
Labeled ID's don't get collected by Cryo's machine [bug]

### ISSUE THREAD

**Issue by OrbisAnima** [SpadesNeil/VOREstation#102] opened 2015-10-10 00:53 UTC
Labeled ID's don't get collected by Cryo's machine, and I don't have an idea why.

**Comment by SpadesNeil** [comment] 2015-10-10 19:24
@Leshana !

**Comment by OrbisAnima** [comment] 2015-10-10 21:43
Been testing, apparently is not about labels, but I found Sebastian Aji's Id on the cryo and I don't know why, there is an exception to the fix I made, maybe has to do with the Vore code? I will test eating an unmonkey with an id and then check if my cryo leaves an id

**Comment by OrbisAnima** [comment] 2015-10-10 22:58
I tested this byond the oblivion, and nothing, I couldn't reproduce how an id appeared on top of cryo on station. I did notice horewer, that items are not savaged if they are in your insides, or on the person that you ate. I tested id's on their uniforms, on their pda's, all five tipes of V, inside their backpacks, inside mine, discovered id's you have in a box inside your backpack are deleted but not stored, and such, but nothing resulted in an id appearing on top of the cryo.

**Comment by Leshana** [comment] 2015-10-11 02:13
What do you mean by "labeled ID" ?    From context I am guessing, do you mean the half-digested ones?

**Comment by Arokha** [comment] 2015-10-11 09:06
I think he meant like if you whap it with a label gun? But said it's not about that so.

**Comment by OrbisAnima** [comment] 2015-10-12 02:52
the situation was as following, I found during one round a labelled(by the hand labeler) id on the cryopod, like we used to have when someone placed it's ID ont heir pda and went to cryo. I talked with the player that labeled it and it told me he did it after it was ejected. So, we have an strange case that I couldn't reproduce locally where the exceptions of ID's aren't working. maybe it was an agent ID? I am not sure, less if we count the id was from sebastian aji, a surgeon...

**Comment by SpadesNeil** [comment] 2015-10-13 22:31
I'm pretty sure the issue is because of PDAs.

The PDAs eject IDs when deleted, when they should remove them and put them into cryo storage also. The PDA must be deleted in order for it not to cause bugs.

**Comment by OrbisAnima** [comment] 2015-10-13 23:39
It gets deleted and most of the time the id is stored, unless the person is inside an stomach, then it gets deleted too

**Comment by SpadesNeil** [comment] 2015-10-18 20:03
I keep seeing IDs on top of the cryo machine seemingly without rhyme or reason.

**Comment by SpadesNeil** [comment] 2016-01-26 04:18
Closing issue since this seems to have been gone a while.

**Closed by SpadesNeil** 2016-01-26 04:18 UTC
Labels: bug, resolved
