### ISSUE TITLE
Insole?

### ISSUE THREAD

**Issue by Rixunie** [SpadesNeil/VOREstation#410] opened 2016-02-27 08:48 UTC
Add the ability to hide micro's/smaller people in your shoes, suits, etc, effectively hiding them from view?

**Comment by OrbisAnima** [comment] 2016-02-28 02:02
a micro is an object.If you want to hide them in your shoes... you need to make shoes a container. Some suits, like the labcoat, already are a container, and thus micros are hideable there, you might get problems in there with talking, whispering and emoting, so test before comiting.

**Comment by SpadesNeil** [comment] 2016-03-13 17:32
Duplicate of #280

**Closed by SpadesNeil** 2016-03-13 17:32 UTC
Labels: duplicate
