### ISSUE TITLE
Clown and Mime Jobs

### ISSUE THREAD

**Issue by SilverTalismen** [SpadesNeil/VOREstation#701] opened 2016-05-05 20:38 UTC
These should totally be added in now that the whitelist stuff is working

(Hopefully Tasy gets a automaticly added to the whitelist for clown~)

((Edit: And clowns should get the genetic tag thing that makes them clutzy and stuff goes wrong when they do basic stuff, like handcuffing someone and they somehow cuff themselvs sort of thing!))

**Comment by SpadesNeil** [comment] 2016-05-06 05:09
Duplicate of #618

**Closed by SpadesNeil** 2016-05-06 05:09 UTC
