### ISSUE TITLE
Racial whitelist broken again

### ISSUE THREAD

**Issue by Cameron653** [SpadesNeil/VOREstation#627] opened 2016-04-26 21:45 UTC
Exactly what it says in the title.
For whatever reason, it'd appear that skeletons, Vox, and Diona aren't actually whitelisted. Possibly caused by the whitelist update.

**Comment by SpadesNeil** [comment] 2016-05-05 06:11
Pretty sure this was resolved.

**Comment by Cameron653** [comment] 2016-05-06 20:43
Just tested it on the server. This bug still exists.

http://puu.sh/oIHRm/b191d9f708.png

**Comment by SpadesNeil** [comment] 2016-05-06 21:00
Were you admin on the test server?

**Comment by Cameron653** [comment] 2016-05-06 22:37
This was on the main server, not the test server. As in, the actual server.

**Comment by SpadesNeil** [comment] 2016-05-07 03:27
Try other species.

**Comment by Cameron653** [comment] 2016-05-07 13:33
Going to test the other species. Will edit with results.

**Comment by SpadesNeil** [comment] 2016-05-07 15:04
Going to close this as it's technically a duplicate of an earlier issue which is being reopened.

**Comment by SpadesNeil** [comment] 2016-05-07 15:06
Okay, no, that was a PR. Not an issue. Wtf. Stupid Github search function.

**Comment by Cameron653** [comment] 2016-05-07 15:07
Er, that's a PR. Not an issue.

**Comment by SpadesNeil** [comment] 2016-05-07 15:07
#29 is what I meant but it's not quite a duplicate.

**Closed** 2016-10-05 22:50 UTC
Labels: Priority: Severe, Type: Bug
